name: OpenWrt-IB-24.10.2-x86_64

on:
  workflow_dispatch:

env:
  IB_BASE_URL: https://downloads.openwrt.org/releases/24.10.2/targets/x86/64
  IB_FILE: openwrt-imagebuilder-24.10.2-x86-64.Linux-x86_64.tar.zst
  IB_DIR: openwrt-imagebuilder-24.10.2-x86-64.Linux-x86_64
  PROFILE: generic   # 注意：不是 generic-efi
  # 包清单（按你要求：DNS/DHCP 用 dnsmasq-full、fw4/nft、Clash/后装Docker所需内核等）
  PACKAGES: >-
    dnsmasq-full -dnsmasq
    firewall4 nftables iptables-nft
    kmod-nf-conntrack kmod-nf-nat kmod-nft-nat kmod-nft-tproxy kmod-nft-socket kmod-nft-offload
    kmod-tun kmod-inet-diag
    ca-bundle ca-certificates curl wget-ssl unzip bash coreutils-nohup ip-full
    luci luci-compat luci-app-firewall
    dockerd containerd
    kmod-veth kmod-br-netfilter
    irqbalance ethtool
    kmod-igc
    kmod-hv-vmbus kmod-hv-netvsc kmod-hv-storvsc

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare host
        run: |
          sudo apt-get update -qq
          sudo apt-get install -yqq xz-utils zstd make git ca-certificates curl

      - name: Download ImageBuilder
        run: |
          echo "Base: $IB_BASE_URL"
          echo "Downloading: $IB_BASE_URL/$IB_FILE"
          curl -fL "$IB_BASE_URL/$IB_FILE" -o "$IB_FILE"
          tar --zstd -xf "$IB_FILE"

      - name: Show IB info (profiles/targets)
        working-directory: ./${{ env.IB_DIR }}
        run: |
          make info || true
          echo "---- Available profiles ----"
          make info | sed -n 's/^Profile: //p' || true

      - name: Put files/ (optional)
        run: |
          mkdir -p "${{ env.IB_DIR }}/files"
          # 如需预置 /etc/config/* 等，这里往 $IB_DIR/files 下放

      - name: Dry-run manifest (catch missing pkgs)
        working-directory: ./${{ env.IB_DIR }}
        run: |
          set -e
          echo "PACKAGES(before)=${PACKAGES}"
          # 先跑 manifest，便于提前发现缺包
          make manifest PROFILE="${PROFILE}" PACKAGES="${PACKAGES}" >manifest.ok 2>manifest.err || true
          if grep -q "Cannot install package" manifest.err; then
            echo "== Manifest errors ==" && cat manifest.err && exit 1
          fi
          # 有时 _check_profile 导致失败且不含 'Cannot install'，再检查一次 Profile 是否存在
          if ! make info | sed -n 's/^Profile: //p' | grep -qx "${PROFILE}"; then
            echo "Profile '${PROFILE}' not found in this IB. Available:" 
            make info | sed -n 's/^Profile: //p'
            exit 1
          fi
          # 到这里基本可以构建了

      - name: Build (EFI & non-EFI 均会产出；如只要 EFI，可加 EFI_IMAGES=y)
        working-directory: ./${{ env.IB_DIR }}
        run: |
          make image PROFILE="${PROFILE}" PACKAGES="${PACKAGES}" \
            BIN_DIR=./bin \
            EXTRA_IMAGE_NAME="$(date +%Y%m%d%H%M)"
          ls -lh bin/targets/*/*

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-24.10.2-x86_64-${{ env.PROFILE }}
          path: ${{ env.IB_DIR }}/bin/targets/*/*/*
