name: IB x86_64 (Docker + OpenClash runtime + Offload)

on:
  workflow_dispatch:

env:
  # ===== 路径/目标 =====
  OWRT_TREE: snapshots          # 用 snapshots；要稳定版可改成 releases/24.10.1
  TARGET: x86
  SUBTARGET: 64
  PROFILES: "generic generic-efi"    # 同时打 BIOS/UEFI；只要其一就删掉另一个
  TZ: Asia/Shanghai

  # ===== 一行包清单（不要换行）=====
  # - OpenClash 运行环境（fw4/nft/tproxy/dnsmasq-full 等）
  # - Docker（dockerd/containerd/内核模块 + Dockerman）
  # - I226 驱动（kmod-igc）
  # - PVE/KVM VirtIO & Hyper-V 驱动
  # - 官方加速（kmod-nft-offload + 开机自动开启，见下方 FILES）
  PACKAGES: "dnsmasq-full -dnsmasq -dnsmasq-dhcpv6 firewall4 nftables iptables-nft kmod-nf-conntrack kmod-nf-nat kmod-nft-nat kmod-nft-tproxy kmod-nft-socket kmod-nft-offload kmod-tun kmod-inet-diag ca-bundle ca-certificates curl wget-ssl unzip bash coreutils-nohup ip-full luci luci-compat luci-app-firewall kmod-igc dockerd docker containerd kmod-bridge kmod-veth kmod-br-netfilter kmod-fs-overlay kmod-fs-ext4 luci-app-dockerman luci-i18n-dockerman-zh-cn irqbalance ethtool kmod-virtio kmod-virtio-net kmod-virtio-blk kmod-virtio-scsi kmod-virtio-console kmod-balloon kmod-hv-vmbus kmod-hv-netvsc kmod-hv-storvsc"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Init build env
        shell: bash
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install -y ca-certificates curl xz-utils zstd tar coreutils
          sudo timedatectl set-timezone "$TZ"
          df -hT

      - name: Download ImageBuilder (.tar.zst, auto-detect)
        shell: bash
        run: |
          set -e
          BASE="https://downloads.openwrt.org/${OWRT_TREE}/targets/${TARGET}/${SUBTARGET}"
          echo "Base: $BASE"
          IB_FILE="$(curl -fsSL "$BASE/" | grep -o 'openwrt-imagebuilder-[^"]*Linux-x86_64\.tar\.zst' | head -n1)"
          test -n "$IB_FILE" || { echo "No ImageBuilder .tar.zst found on $BASE"; exit 8; }
          echo "Downloading: $BASE/$IB_FILE"
          curl -fL --retry 5 --retry-delay 2 -o ib.tar.zst "$BASE/$IB_FILE"
          tar --zstd -xf ib.tar.zst
          IB_DIR="$(tar -tf ib.tar.zst | head -n1 | cut -d/ -f1)"
          echo "IB_DIR=$IB_DIR" >> $GITHUB_ENV
          echo "IB_DIR=$IB_DIR"

      # （可选）切换国内镜像：把下一步的 if 改成 'always()' 即可启用
      - name: (optional) Switch repositories to BFSU mirror
        if: false
        shell: bash
        run: |
          set -e
          cd "$IB_DIR"
          sed -i 's#https://downloads.openwrt.org#https://mirrors.bfsu.edu.cn/openwrt#g' repositories.conf

      - name: Prepare FILES (enable flow offload on boot; docker bridge sysctl)
        shell: bash
        run: |
          set -e
          cd "$IB_DIR"
          # 合并用户自带 files/（若仓库中存在）
          if [ -d "${GITHUB_WORKSPACE}/files" ]; then
            cp -a "${GITHUB_WORKSPACE}/files" .
          else
            mkdir -p files
          fi
          # 开机启用软件/硬件 flow offload
          mkdir -p files/etc/uci-defaults
          cat > files/etc/uci-defaults/99-flow-offload << 'EOF'
          #!/bin/sh
          uci -q set firewall.@defaults[0].flow_offloading='1'
          uci -q set firewall.@defaults[0].flow_offloading_hw='1'
          uci -q commit firewall
          exit 0
          EOF
          chmod +x files/etc/uci-defaults/99-flow-offload

          # docker 桥过滤（通常内核默认已启，此处保险）
          mkdir -p files/etc/sysctl.d
          cat > files/etc/sysctl.d/90-bridge-nf.conf << 'EOF'
          net.bridge.bridge-nf-call-iptables=1
          net.bridge.bridge-nf-call-ip6tables=1
          EOF

      - name: (optional) Local pkgs repo (auto-index pkgs/*.ipk e.g. luci-app-openclash)
        shell: bash
        run: |
          set -e
          cd "$IB_DIR"
          if [ -d "${GITHUB_WORKSPACE}/pkgs" ]; then
            mkdir -p pkgs
            cp -a "${GITHUB_WORKSPACE}/pkgs/"* pkgs/ || true
          fi
          if [ -d pkgs ] && ls pkgs/*.ipk >/dev/null 2>&1; then
            echo "[IB] Found local ipk(s); building local repo..."
            ./staging_dir/host/bin/opkg-make-index pkgs > pkgs/Packages
            gzip -9c pkgs/Packages > pkgs/Packages.gz
            echo "src custom file:pkgs" >> repositories.conf
            # 想把 openclash 也打进固件：把 'luci-app-openclash' 加到 env.PACKAGES 一行里即可
          else
            echo "[IB] No pkgs/*.ipk provided; skip local repo."
          fi

      - name: Build images
        shell: bash
        run: |
          set -e
          cd "$IB_DIR"
          echo "PACKAGES=${PACKAGES}"
          for p in ${PROFILES}; do
            echo "=== Build profile: $p ==="
            make image PROFILE="$p" PACKAGES="${PACKAGES}" FILES=files/ || { echo "Build failed: $p"; exit 1; }
          done
          ls -lh bin/targets/${TARGET}/${SUBTARGET}/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: IB-x86_64-openclash-docker-${{ github.run_id }}
          path: ${{ env.IB_DIR }}/bin/targets/${{ env.TARGET }}/{{ env.SUBTARGET }}/*
