    - name: "Fail-fast: block rust/host by config"
      working-directory: ./openwrt
      shell: bash
      run: |
        set -e
        make defconfig
        awk -v RS='' '/^Package:/ {p=$2} /Build-Depends:.*rust\/host/ {print p}' tmp/.packageinfo \
          | sort -u > /tmp/need_rust.txt || true
        sed -n 's/^CONFIG_PACKAGE_\(.*\)=y/\1/p' .config | sort > /tmp/enabled_all.txt
        echo "---- Packages declaring rust/host (candidates) ----"
        cat /tmp/need_rust.txt || true
        if grep -Fxf /tmp/need_rust.txt /tmp/enabled_all.txt >/dev/null 2>&1; then
          echo "✗ These packages in .config would trigger rust/host:"
          grep -Fxf /tmp/need_rust.txt /tmp/enabled_all.txt || true
          exit 1
        else
          echo "✓ No rust/host triggers in current .config"
        fi
        echo "---- diffconfig ----"
        ./scripts/diffconfig.sh || true
